# Numpy 簡介

### Numpy 是 Numerical Python 的簡稱，是 Python 用來作科學運算的基礎套件。

#### 這一份筆記主要說明以下重點：

* 為何需要 Numpy？
* Numpy 比 pure python 提供了那些不一樣的東西？
* 怎麼使用 Numpy 的 ndarray？
* 投資理財相關領域中常用的 Numpy 的函式有哪些？

#### 參考資料：

* [Numpy 官網](http://www.numpy.org/)
* [Numpy 教學](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [Python Numpy Array Tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutoria)

## 為什麼需要 Numpy?

### 關於向量運算：

在工程、科學及金融領域，需要用到很多向量運算。簡單說明如下：

假設有兩個向量 (Vectors) A 跟 B，

$A = \left(
    \begin{array}{c}
      a_1 \\
      a_2 \\
      a_3
    \end{array}
  \right)
$

$B = \left(
    \begin{array}{c}
      b_1 \\
      b_2 \\
      b_3
    \end{array}
  \right)
$

向量加法運算如下：

$A + B = \left(
    \begin{array}{c}
      a_1 + b_1 \\
      a_2 + b_2 \\
      a_3 + b_3
    \end{array}
  \right)
$

向量的純量積算法如下：

$c \cdot A = 
  \left(
    \begin{array}{c}
      ca_1 \\
      ca_2 \\
      ca_3
    \end{array}
  \right)
$

### 1. python 的 list 沒有辦法直接作向量運算。

In [1]:
import numpy as np

In [ ]:
A = [1, 2, 3]
B = [4, 5, 6]
A + B

In [ ]:
A * 2

### 2. 替代性的方法運算速度緩慢

In [ ]:
C = []
for i, j in zip(A, B):
    C.append(i + j)
C

In [ ]:
D = []
for i in A:
    D.append(i * 2)
D

### 3. Numpy 提供簡易即迅速的方式執行上面那些向量運算

In [ ]:
A1 = np.array(A)
B1 = np.array(B)
A1 + B1

In [ ]:
A1 * 2

## Numpy 提供了什麼不一樣的東西？

#### Numpy 中主要提供了一個叫做多維陣列 ndarray, or Multi-dimensional Array 的資料結構，透過它可以直接作向量運算。
#### ndarray 有兩個重要的屬性 dtype 及 shape，dtype 為 ndarry 裡面的資料的型態，而 shape 則為資料的形狀。
#### 底下會用例子加以說明。

### Numpy 中的兩大概念：

* 資料結構
  - ndarray
    - dtype
    - shape


* 通用函式
  - ufunc
  

### 如何創建 ndarray？

### 最簡單的方法就是使用 Numpy 的 array 函式。

In [ ]:
X = [1, 2, 3]
Y = np.array(X)
Y

In [ ]:
Z = np.array([4, 5, 6])
Z

In [ ]:
Z.dtype

In [ ]:
Z.shape

### 其他的創建方式

|函式|說明|
|:-|:-|
|array|將輸入的資料轉換成 ndarray。|
|arange|range 的 ndarray 版。|
|ones, ones_like|創建一個全部是1的ndarray。|
|zeros, zeros_like|創建一個全部是0的ndarray。|
|empty, empty_like|創建一個未填入資料的ndarray。|
|eye, identity|創建一個單位矩陣。|

In [ ]:
I = np.eye(4)
I

In [ ]:
I.shape

In [ ]:
G = np.arange(25)
G

In [ ]:
G.shape

In [ ]:
F = G.reshape(5, 5)
F

In [ ]:
G

In [ ]:
G.shape = 5, 5
G

### ndarray 的 indexing

In [ ]:
G[1, 1]

In [ ]:
G[1][1]

### ndarray 的 slicing

In [ ]:
G[0]

In [ ]:
G[0, :]

In [ ]:
G[:, 0]

In [ ]:
G[:][0]

In [ ]:
G[1:3, 1:3]

### ndarray 的 boolean indexing

In [ ]:
G > 10

In [ ]:
G[G > 10]

In [ ]:
np.where(G > 10, G, 0)

In [ ]:
np.all(G > -1)

In [ ]:
np.all(G < 25)

In [ ]:
np.all(G > 0)

In [ ]:
np.any(G > 0)

### 什麼是 ufunc？

* universal function 的縮寫
* 用來對 ndarray 裡面的每個元素作操作的函式。
* ufunc 可以被看作是一般 python 函式的向量化版本。
* Numpy 的 ufunc 都是衍生自 numpy.ufunc 類別。
* 很多內建的 ufunc 底層都是使用 C 實作的，所以速度很快。

詳細內容請參考：[ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [ ]:
isinstance(np.sin, np.ufunc)

In [ ]:
isinstance(np.arange, np.ufunc)

In [ ]:
import math
math.pi

In [ ]:
K = np.arange(0, 2, 0.1)
K = K * math.pi
K

In [ ]:
np.sin(K)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(np.sin(K))

### numpy 有哪些 ufuncs？

想知道 numpy 有哪些 ufunc ，可以參考官網上面的連結：[Available ufuncs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs)

## 金融投資相關領域中常用的 numpy 函式有哪些？

* [Numpy 的函式列表](https://docs.scipy.org/doc/numpy/reference/routines.html)

### 統計相關函式

參考：[Statistics](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.statistics.html)

|函式|說明|
|:-|:-|
|sum|總和|
|mean|平均|
|std|標準差|
|var|變異數|
|min, max|最小值、最大值|
|argmin, argmax|最小值的索引、最大值的索引|
|cumsum|和的累計值|
|cumprod|積的累計值|

In [2]:
a = [1, 2, 3, 4, 5]

In [3]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [4]:
np.cumprod(a)

array([  1,   2,   6,  24, 120], dtype=int32)

In [7]:
import pandas as pd

In [8]:
b = pd.Series([1, 1.1, 1.2, 1.3, 1.4, 1.5])

In [10]:
c = b.pct_change().values

In [14]:
c

array([       nan, 0.1       , 0.09090909, 0.08333333, 0.07692308,
       0.07142857])

In [13]:
np.cumprod(1+c[1:])

array([1.1, 1.2, 1.3, 1.4, 1.5])

### 亂數相關函式

參考：[Random Sampling (numpy.random)](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

|函式|說明|
|:-|:-|
|[seed](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html#numpy.random.seed)|設定亂數的種子|
|[permutation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.permutation.html)|隨機排列|
|[shuffle](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.shuffle.html)|沿著 axis 0 的隨機排列|
|[rand](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand)|返回指定形狀的亂數，亂數值為[0,1]間的均勻分布|
|[randn](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html#numpy.random.randn)|返回指定形狀的亂數，亂數值為mean為0，variance為1的高斯分布|
|[randint](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html#numpy.random.randint)|使用離散均勻分布，返回指定形狀的整數亂數|
|[normal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html#numpy.random.normal)|返回指定形狀的亂數，亂數值為自訂的mean跟variance的高斯分布|
|[uniform](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html#numpy.random.uniform)|使用均勻分布，返回指定形狀的亂數|

In [ ]:
np.random.seed(10)
np.random.rand(5)